#!/usr/bin/env python3
"""Recover exact published old consumer bytes for a future Linux compatibility gate."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import urllib.request
from artifacts import sha_file,inventory

SOURCE=Path(__file__).with_name('historical')
LOCK_SHA='e4e416530d4dee347afd7c1acbe6d36b8baf3807f2eed2588250f1ca6b4a810f'
MATERIALIZER_SHA='5a68c026870070d39ecb13eacf09a5300fe8e25235f27bdbd708b1465288d0a7'
PROBE_SHA='c7bd1a15063e464ebc21bd09c38421d9196fbc2ae905cd4833cb7ded97b2e349'


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--work',type=Path,required=True)
    p.add_argument('--output',type=Path,required=True);p.add_argument('--asset',type=Path)
    p.add_argument('--execute-fresh-linux-ci',action='store_true');a=p.parse_args()
    if not a.execute_fresh_linux_ci or sys.platform!='linux' or os.environ.get('CI')!='true':p.error('explicit fresh Linux CI execution only')
    for name,digest in [('HISTORICAL_CONSUMER_LOCK.json',LOCK_SHA),('materialize_historical_client.py',MATERIALIZER_SHA),('historical_runtime_probe.py',PROBE_SHA)]:
        if (SOURCE/name).is_symlink() or sha_file(SOURCE/name)!=digest:raise ValueError('historical tool/lock differs from reviewed pinned input')
    work=a.work.resolve();out=a.output.resolve()
    if work.is_relative_to(out) or out.is_relative_to(work):raise ValueError('history work/output roots must be disjoint')
    work.mkdir(parents=True,exist_ok=False);out.mkdir(parents=True,exist_ok=False)
    lock=json.loads((SOURCE/'HISTORICAL_CONSUMER_LOCK.json').read_text());asset=a.asset.resolve(strict=True) if a.asset else work/lock['release']['asset_name']
    if not a.asset:
        with urllib.request.urlopen(lock['release']['url'],timeout=120) as source,asset.open('xb') as output:
            shutil.copyfileobj(source,output,1024*1024)
    if asset.is_symlink() or asset.stat().st_size!=lock['release']['bytes'] or sha_file(asset)!=lock['release']['sha256']:
        raise ValueError('exact preserved/published historical asset required; latest fallback forbidden')
    env=dict(os.environ,PYTHONDONTWRITEBYTECODE='1')
    result=subprocess.run([sys.executable,'-B',str(SOURCE/'materialize_historical_client.py'),'--asset',str(asset),'--output',str(out/'client')],
                          env=env,capture_output=True,text=True)
    (work/'materialize.stdout').write_text(result.stdout);(work/'materialize.stderr').write_text(result.stderr)
    if result.returncode:raise RuntimeError('historical static materialization failed; no old consumer code was run')
    receipt=json.loads(result.stdout)
    if receipt['classification']!='PUBLISHED_INSTALLED_RUNTIME_CLIENT' or receipt['runtime_executed'] is not False:raise ValueError('historical recovery classification differs')
    expected={row['name'] for row in lock['files']}
    if set(p.name for p in (out/'client').iterdir())!=expected:raise ValueError('extra historical client source or generated bytecode')
    for row in lock['files']:
        file=out/'client'/row['name']
        if file.is_symlink() or file.stat().st_size!=row['bytes'] or sha_file(file)!=row['sha256']:raise ValueError('historical client bytes differ')
        if file.stat().st_mode & 0o222:raise ValueError('historical client must be materialized without write permission')
    for name in ('HISTORICAL_CONSUMER_LOCK.json','historical_runtime_probe.py'):shutil.copyfile(SOURCE/name,out/name)
    # Exact old license text is recovered from the same authenticated-by-pin
    # original release archive; never silently use current release legal text.
    import tarfile
    with tarfile.open(asset,'r:gz') as stream:
        for name in ('LICENSE','NOTICE'):
            path='rx-linux-dev/sources/solutions/'+name;matches=[m for m in stream.getmembers() if m.name==path]
            if len(matches)!=1 or not matches[0].isfile():raise ValueError('historical license closure differs')
            (out/name).write_bytes(stream.extractfile(matches[0]).read())
    (out/'ORIGIN.json').write_text(json.dumps({'schema':'rx.m5-historical-client-origin.v1','classification':receipt['classification'],
        'original_asset':lock['release'],'materialization':receipt,'tools':{'materializer_sha256':MATERIALIZER_SHA,'probe_sha256':PROBE_SHA,'lock_sha256':LOCK_SHA},
        'runtime_compatibility':'NOT_RUN','new_sdk_relabelled_as_old':False,'public_provenance_signature':'Use preserved release signature receipt separately'},indent=2)+'\n')
    (work/'result.json').write_text(json.dumps({'status':'HISTORICAL_BYTES_MATERIALIZED_NOT_EXECUTED','inventory':inventory(out)},indent=2)+'\n')
    print(json.dumps({'status':'HISTORICAL_BYTES_MATERIALIZED_NOT_EXECUTED','client_files':len(expected)}))


if __name__=='__main__':main()
